plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
    id 'maven-publish'
    id("java")
	id("com.wynprice.cursemaven") version "2.1.5"
    //TODO: FIX id 'xyz.wagyourtail.unimined' version '1.4.1'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
        content {
            includeGroup "com.klikli_dev"
        }
    }
    maven {
        url "https://maven2.bai.lol"
        content {
            includeGroup "lol.bai"
            includeGroup "mcp.mobius.waila"
        }
    }
    maven {
        url "https://cursemaven.com"
    }
    maven {
        url = "https://www.curseforge.com/api/maven/"
    }
    maven {
        url 'https://maven.azuredoom.com/mods'
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url = "https://dl.cloudsmith.io/public/tslat/sbl/maven/"
    }
    maven {
        url "https://maven.terraformersmc.com/releases"
    }
    maven {
        url "https://maven.ryanliptak.com"
    }
    maven {
        url "https://maven.shedaniel.me"
    }
    maven {
        url = "https://maven.blamejared.com/"
    }
    maven {
        url = "https://maven.neoforged.net/releases"
    }
    maven {
        url = "https://maven.minecraftforge.net/"
    }
    maven {
        url = "https://maven.fabricmc.net/"
    }
    maven {
        url = "https://maven.wagyourtail.xyz/releases"
    }
    maven {
        url = "https://maven.wagyourtail.xyz/snapshots"
    }
    gradlePluginPortal() {
        content {
            excludeGroup("org.apache.logging.log4j")
        }
    }
    maven {
        url = "https://modmaven.dev"
    }
    maven {
        url "https://api.modrinth.com/maven"
    }
    maven {
        url = 'https://oss.sonatype.org/content/repositories/snapshots'
    }
    maven {
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        url "https://jitpack.io"
    }
    maven {
        url "https://maven.terraformersmc.com/releases"
    }
    maven {
        url "https://uncomfortable-fey-midnight145-884fba2b.koyeb.app"
        content {
            includeGroup "curse.fetch"
        }
    }
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release"
    }
    maven {
        url "https://beta.cursemaven.com"
    }
    maven {
        url "https://maven.architectury.dev/"
    }
    maven {
        url "https://mvn.devos.one/snapshots"
    }
    /*maven { // errors w/ 500
url "https://archive.naylahanegan.com/0:/"
} */
    maven {
        url "https://mcmodarchive.femtopedia.de/"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'GeckoLib'
                url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            }
        }
        filter {
            includeGroup('software.bernie.geckolib')
        }
    }
    maven {
        url "https://maven.wispforest.io/releases"
    }
    maven {
        url "https://maven.parchmentmc.org"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "witcheskitchen" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    accessWidenerPath = file("src/main/resources/wk.accesswidener")
}

fabricApi {
    configureDataGeneration()
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    /*modImplementation("com.klikli_dev:modonomicon-${minecraft_version}-fabric:${modonomicon_version}") {
// Exclude JEI transitive dependency, as otherwise, the game will not launch in dev.
exclude group: "mezz.jei"
}*/ // TODO: not updated
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
    //modImplementation "com.github.Virtuoel:Pehkui:${pehkui_version}" // not needed on >=1.21.2
    modCompileOnly "squeek.appleskin:appleskin-fabric:${appleskin_version}:api"
    //include modApi("maven.modrinth:impersonate:${impersonate_version}") // TODO: not updated
    include modApi("maven.modrinth:midnightlib:${midnightlib_version}")
    modImplementation "io.wispforest:owo-lib:${owo_version}"
    modImplementation "io.wispforest:accessories-fabric:${accessories_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-world:${project.cca_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-scoreboard:${project.cca_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-chunk:${project.cca_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-block:${project.cca_version}"
    modCompileOnly "mcp.mobius.waila:wthit-api:fabric-${wthitVersion}"
    modRuntimeOnly "mcp.mobius.waila:wthit:fabric-${wthitVersion}"
    modRuntimeOnly "lol.bai:badpackets:fabric-${badpacketsVersion}"
    modCompileOnlyApi "me.shedaniel:RoughlyEnoughItems-api-fabric:$rei_version"
    modCompileOnlyApi "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:$rei_version"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"
    modCompileOnly "dev.architectury:architectury-fabric:$architectury_version"
    modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:$cloth_version") {
        // required for making REI integration work
        exclude(group: "net.fabricmc.fabric-api")
    }
    // JEI is unavailable for Fabric on 1.21.5
    //modCompileOnlyApi("mezz.jei:jei-${mc_version}-common-api-intermediary:${jei_version}")
    //modCompileOnlyApi("mezz.jei:jei-${mc_version}-fabric-api:${jei_version}")
    //modRuntimeOnly("mezz.jei:jei-${mc_version}-fabric:${jei_version}")
    // EMI is not updated for 1.21.5
    //modCompileOnlyApi "dev.emi:emi-fabric:${emi_version}:api"
    include modImplementation("io.github.ladysnake:PlayerAbilityLib:${pal_version}")
    include modApi("me.lucko:fabric-permissions-api:${fabric_permissions_api_version}")
    //modImplementation "mod.azure.azurelib:azurelib-fabric-${minecraft_version}:${azurelib_version}"
    modImplementation "software.bernie.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}"
    //modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${minecraft_version}:${smartbrainlib_version}"
    modImplementation "maven.modrinth:smartbrainlib:${smartbrainlib_version}"
}

processResources {
    filesMatching("fabric.mod.json") {
        expand(project.properties)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}