# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

### Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2
mc_version=1.21.8

### Mod Properties
mod_version=1.0.0
maven_group=cf.witcheskitchen
archives_base_name=WitchesKitchen

### Dependencies
# https://linkie.shedaniel.dev/dependencies?loader=fabric&version=1.21.8
fabric_version=0.131.0+1.21.8
rei_version=20.0.811
modmenu_version=15.0.0-beta.3
cloth_version=19.0.147
architectury_version=17.0.8

# https://modrinth.com/mod/modonomicon/versions?g=1.21.8
#modonomicon_version=1.117.2 # TODO: not updated

# https://modrinth.com/mod/pehkui/versions?g=1.21.8
#pehkui_version=3.8.3

# https://maven.ryanliptak.com/squeek/appleskin/appleskin-fabric/
appleskin_version=mc1.21.6-3.0.6

# https://modrinth.com/mod/midnightlib/versions?g=1.21.8&l=fabric
midnightlib_version=1.7.5+1.21.6-fabric

# https://modrinth.com/mod/geckolib/versions?g=1.21.8
geckolib_version=5.2.2

# https://maven.wispforest.io/#/releases/io/wispforest/owo-lib
owo_version=0.12.22+1.21.8

# https://maven.wispforest.io/#/releases/io/wispforest/accessories-fabric
accessories_version=1.3.3-beta+1.21.8

# https://modrinth.com/mod/impersonate/versions?g=1.21.8
#impersonate_version=3.3.0 # TODO: not updated

# https://modrinth.com/mod/cardinal-components-api/versions?g=1.21.8
cca_version=7.0.0-beta.1

# https://modrinth.com/mod/wthit/versions?g=1.21.8&l=fabric
wthitVersion=16.0.1

# https://modrinth.com/mod/badpackets/versions?g=1.21.x&l=fabric
badpacketsVersion=0.9.0

# https://modrinth.com/mod/jei/versions?g=1.21.8&l=fabric
# jei_version=19.21.0.247

# https://modrinth.com/mod/emi/versions?g=1.21.8&l=fabric
#emi_version=1.1.18+1.21.1

# https://github.com/Ladysnake/PlayerAbilityLib/releases
pal_version=1.14.0

# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_api_version=0.4.1

# https://modrinth.com/mod/smartbrainlib/versions?g=1.21.8
#smartbrainlib_version=1.16.10
# FIXME: SmartBrainLib doesn't seem to be published to an accessible maven..
smartbrainlib_version=9GQtntXj