# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
### Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
parchment_version=2025.10.12
loader_version=0.17.3
mc_version=1.21.10
### Mod Properties
mod_version=1.0.0
maven_group=cf.witcheskitchen
archives_base_name=WitchesKitchen
### Dependencies
# https://linkie.shedaniel.dev/dependencies?loader=fabric&version=1.21.10
fabric_version=0.136.0+1.21.10
rei_version=20.0.811
modmenu_version=16.0.0-rc.1
cloth_version=20.0.148
architectury_version=18.0.5
# https://modrinth.com/mod/modonomicon/versions?g=1.21.10
modonomicon_version=1.119.1
# https://modrinth.com/mod/pehkui/versions?g=1.21.10
#pehkui_version=3.8.3
# https://maven.ryanliptak.com/squeek/appleskin/appleskin-fabric/
appleskin_version=mc1.21.9-3.0.7
# https://modrinth.com/mod/midnightlib/versions?g=1.21.10&l=fabric
midnightlib_version=1.8.3+1.21.9-fabric
# https://modrinth.com/mod/geckolib/versions?g=1.21.10
geckolib_version=5.3-alpha-2
# https://maven.wispforest.io/#/releases/io/wispforest/owo-lib
owo_version=0.13.0-alpha.8+1.21.9
# https://maven.wispforest.io/#/releases/io/wispforest/accessories-fabric
accessories_version=1.4.0-beta+1.21.10
# https://modrinth.com/mod/impersonate/versions?g=1.21.10
#impersonate_version=3.3.0 # TODO: not updated
# https://modrinth.com/mod/cardinal-components-api/versions?g=1.21.10
cca_version=7.2.0
# https://modrinth.com/mod/wthit/versions?g=1.21.10&l=fabric
wthitVersion=17.2.0
# https://modrinth.com/mod/badpackets/versions?g=1.21.x&l=fabric
badpacketsVersion=0.10.2
# https://modrinth.com/mod/jei/versions?g=1.21.10&l=fabric
# jei_version=19.21.0.247
# https://modrinth.com/mod/emi/versions?g=1.21.10&l=fabric
#emi_version=1.1.18+1.21.1
# https://github.com/Ladysnake/PlayerAbilityLib/releases
pal_version=1.15.0
# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_api_version=0.5.0
# https://modrinth.com/mod/smartbrainlib/versions?g=1.21.10
#smartbrainlib_version=1.16.10
# FIXME: SmartBrainLib doesn't seem to be published to an accessible maven..
smartbrainlib_version=mEykJdJI