# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

### Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.2
loader_version=0.16.9
mc_version=1.21.4

### Mod Properties
mod_version=1.0.0
maven_group=cf.witcheskitchen
archives_base_name=WitchesKitchen

### Dependencies
# https://linkie.shedaniel.dev/dependencies?loader=fabric&version=1.21.4
fabric_version=0.113.0+1.21.4
rei_version=18.0.796
modmenu_version=13.0.0
cloth_version=17.0.144
architectury_version=15.0.1

# https://modrinth.com/mod/modonomicon/versions?g=1.21.4
modonomicon_version=1.116.0

# https://modrinth.com/mod/pehkui/versions?g=1.21.4
pehkui_version=3.8.3

# https://maven.ryanliptak.com/squeek/appleskin/appleskin-fabric/
appleskin_version=mc1.21.3-3.0.6

# https://modrinth.com/mod/midnightlib/versions?g=1.21.4&l=fabric
midnightlib_version=1.6.6-fabric

# https://maven.azuredoom.com/#/mods/mod/azure/azurelib/azurelib-fabric-1.21.4
azurelib_version=2.3.27

# https://modrinth.com/mod/trinkets/versions?g=1.21.4
trinkets_version=3.10.0

# https://modrinth.com/mod/impersonate/versions?g=1.21.4
impersonate_version=3.3.0

# https://modrinth.com/mod/cardinal-components-api/versions?g=1.21.4
cca_version=6.2.2

# https://modrinth.com/mod/wthit/versions?g=1.21.4&l=fabric
wthitVersion=14.0.1

# https://modrinth.com/mod/badpackets/versions?g=1.21.x&l=fabric
badpacketsVersion=0.8.2

# https://modrinth.com/mod/jei/versions?g=1.21.4&l=fabric
jei_version=19.21.0.247

# https://modrinth.com/mod/emi/versions?g=1.21.4&l=fabric
emi_version=1.1.18+1.21.1

# https://github.com/Ladysnake/PlayerAbilityLib/releases
pal_version=1.11.0

# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_api_version=0.3.3

# https://modrinth.com/mod/smartbrainlib/versions?g=1.21.4
smartbrainlib_version=1.16.5